In [494]:
english_test_score = pd.read_csv('English_Language_Arts__ELA__Test_Results_2006-2012_-_District_-_All_Students.csv')
english_test_score.info()english_test_score

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1568 entries, 0 to 1567
Data columns (total 16 columns):
District             1568 non-null int64
Grade                1568 non-null object
Year                 1568 non-null int64
Demographic          1568 non-null object
Number Tested        1568 non-null int64
Mean Scale Score     1568 non-null int64
Num Level 1          1568 non-null int64
Pct Level 1          1568 non-null float64
Num Level 2          1568 non-null int64
Pct Level 2          1568 non-null float64
Num Level 3          1568 non-null int64
Pct Level 3          1568 non-null float64
Num Level 4          1568 non-null int64
Pct Level 4          1568 non-null float64
Num Level 3 and 4    1568 non-null int64
Pct Level 3 and 4    1568 non-null float64
dtypes: float64(5), int64(9), object(2)
memory usage: 208.2+ KB

In [495]:
english_2006_score = english_test_score.groupby(['District' , 'Grade' , 'Year']).mean()

                          Number Tested  Mean Scale Score  Num Level 1  \
District Grade      Year
1        3          2006            808               663           89
                    2007            826               659           94
                    2008            852               662           60
                    2009            901               667           45
                    2010            848               669          137
                    2011            813               665          103
                    2012            856               663          123
         4          2006            819               654          103
                    2007            860               655           70
                    2008            843               657           74
                    2009            841               664           41
                    2010            892               669           90
                    2011            853               672           81
                    2012            812               674           74
         5          2006            751               651           68
                    2007            854               657           61
                    2008            849               663           21
                    2009            802               674            2
                    2010            793               672          124
                    2011            858               668           85
                    2012            833               669           95
         6          2006            855               653           58
                    2007            785               654           20
                    2008            867               655           23
                    2009            881               667            1
                    2010            784               664          108
                    2011            814               662          108
                    2012            897               663          112
         7          2006            919               646           85
                    2007            899               650           57
...                                 ...               ...          ...
32       5          2011           1292               664          178
                    2012           1296               664          185
         6          2006           1494               640          210
                    2007           1540               643           95
                    2008           1617               648           63
                    2009           1572               659            3
                    2010           1333               654          320
                    2011           1377               654          357
                    2012           1321               656          243
         7          2006           1445               630          271
                    2007           1615               638          207
                    2008           1529               650           41
                    2009           1565               656            9
                    2010           1501               657          269
                    2011           1323               654          278
                    2012           1335               656          231
         8          2006           1584               632          315
                    2007           1507               631          268
                    2008           1500               644          138
                    2009           1530               649           62
                    2010           1553               645          316
                    2011           1513               645          227
                    2012           1259               648          169
         All Grades 2006           8438               639         1331
                    2007           9179               641         1203
                    2008           8897               648          643
                    2009           8652               656          285
                    2010           8304               656         1635
                    2011           8046               655         1452
                    2012           7688               657         1225

                          Pct Level 1  Num Level 2  Pct Level 2  Num Level 3  \
District Grade      Year
1        3          2006         11.0          215         26.6          462
                    2007         11.4          242         29.3          427
                    2008          7.0          270         31.7          449
                    2009          5.0          221         24.5          553
                    2010         16.2          276         32.5          272
                    2011         12.7          265         32.6          371
                    2012         14.4          294         34.3          379
         4          2006         12.6          272         33.2          405
                    2007          8.1          286         33.3          469
                    2008          8.8          251         29.8          480
                    2009          4.9          216         25.7          533
                    2010         10.1          386         43.3          372
                    2011          9.5          313         36.7          420
                    2012          9.1          296         36.5          392
         5          2006          9.1          286         38.1          342
                    2007          7.1          293         34.3          461
                    2008          2.5          210         24.7          571
                    2009          0.2          144         18.0          556
                    2010         15.6          308         38.8          252
                    2011          9.9          322         37.5          393
                    2012         11.4          277         33.3          406
         6          2006          6.8          346         40.5          363
                    2007          2.5          365         46.5          344
                    2008          2.7          382         44.1          426
                    2009          0.1          223         25.3          562
                    2010         13.8          334         42.6          269
                    2011         13.3          309         38.0          340
                    2012         12.5          329         36.7          414
         7          2006          9.2          425         46.2          341
                    2007          6.3          390         43.4          418
...                               ...          ...          ...          ...
32       5          2011         13.8          568         44.0          500
                    2012         14.3          533         41.1          547
         6          2006         14.1          647         43.3          557
                    2007          6.2          854         55.5          551
                    2008          3.9          784         48.5          745
                    2009          0.2          463         29.5         1042
                    2010         24.0          554         41.6          433
                    2011         25.9          557         40.5          444
                    2012         18.4          598         45.3          467
         7          2006         18.8          687         47.5          462
                    2007         12.8          757         46.9          606
                    2008          2.7          699         45.7          772
                    2009          0.6          562         35.9          970
                    2010         17.9          749         49.9          415
                    2011         21.0          669         50.6          360
                    2012         17.3          684         51.2          403
         8          2006         19.9          766         48.4          484
                    2007         17.8          805         53.4          412
                    2008          9.2          781         52.1          528
                    2009          4.1          667         43.6          775
                    2010         20.3          790         50.9          417
                    2011         15.0          891         58.9          390
                    2012         13.4          704         55.9          386
         All Grades 2006         15.8         3650         43.3         3250
                    2007         13.1         4302         46.9         3492
                    2008          7.2         3848         43.3         4204
                    2009          3.3         2963         34.2         5110
                    2010         19.7         3842         46.3         2487
                    2011         18.0         3827         47.6         2671
                    2012         15.9         3601         46.8         2766

                          Pct Level 3  Num Level 4  Pct Level 4  \
District Grade      Year
1        3          2006         57.2           42          5.2
                    2007         51.7           63          7.6
                    2008         52.7           73          8.6
                    2009         61.4           82          9.1
                    2010         32.1          163         19.2
                    2011         45.6           74          9.1
                    2012         44.3           60          7.0
         4          2006         49.5           39          4.8
                    2007         54.5           35          4.1
                    2008         56.9           38          4.5
                    2009         63.4           51          6.1
                    2010         41.7           44          4.9
                    2011         49.2           39          4.6
                    2012         48.3           50          6.2
         5          2006         45.5           55          7.3
                    2007         54.0           39          4.6
                    2008         67.3           47          5.5
                    2009         69.3          100         12.5
                    2010         31.8          109         13.7
                    2011         45.8           58          6.8
                    2012         48.7           55          6.6
         6          2006         42.5           88         10.3
                    2007         43.8           56          7.1
                    2008         49.1           36          4.2
                    2009         63.8           95         10.8
                    2010         34.3           73          9.3
                    2011         41.8           57          7.0
                    2012         46.2           42          4.7
         7          2006         37.1           68          7.4
                    2007         46.5           34          3.8
...                               ...          ...          ...
32       5          2011         38.7           46          3.6
                    2012         42.2           31          2.4
         6          2006         37.3           80          5.4
                    2007         35.8           40          2.6
                    2008         46.1           25          1.5
                    2009         66.3           64          4.1
                    2010         32.5           26          2.0
                    2011         32.2           19          1.4
                    2012         35.4           13          1.0
         7          2006         32.0           25          1.7
                    2007         37.5           45          2.8
                    2008         50.5           17          1.1
                    2009         62.0           24          1.5
                    2010         27.6           68          4.5
                    2011         27.2           16          1.2
                    2012         30.2           17          1.3
         8          2006         30.6           19          1.2
                    2007         27.3           22          1.5
                    2008         35.2           53          3.5
                    2009         50.7           26          1.7
                    2010         26.9           30          1.9
                    2011         25.8            5          0.3
                    2012         30.7            0          0.0
         All Grades 2006         38.5          207          2.5
                    2007         38.0          182          2.0
                    2008         47.3          202          2.3
                    2009         59.1          294          3.4
                    2010         29.9          340          4.1
                    2011         33.2           96          1.2
                    2012         36.0           96          1.2

                          Num Level 3 and 4  Pct Level 3 and 4
District Grade      Year
1        3          2006                504               62.4
                    2007                490               59.3
                    2008                522               61.3
                    2009                635               70.5
                    2010                435               51.3
                    2011                445               54.7
                    2012                439               51.3
         4          2006                444               54.2
                    2007                504               58.6
                    2008                518               61.4
                    2009                584               69.4
                    2010                416               46.6
                    2011                459               53.8
                    2012                442               54.4
         5          2006                397               52.9
                    2007                500               58.5
                    2008                618               72.8
                    2009                656               81.8
                    2010                361               45.5
                    2011                451               52.6
                    2012                461               55.3
         6          2006                451               52.7
                    2007                400               51.0
                    2008                462               53.3
                    2009                657               74.6
                    2010                342               43.6
                    2011                397               48.8
                    2012                456               50.8
         7          2006                409               44.5
                    2007                452               50.3
...                                     ...                ...
32       5          2011                546               42.3
                    2012                578               44.6
         6          2006                637               42.6
                    2007                591               38.4
                    2008                770               47.6
                    2009               1106               70.4
                    2010                459               34.4
                    2011                463               33.6
                    2012                480               36.3
         7          2006                487               33.7
                    2007                651               40.3
                    2008                789               51.6
                    2009                994               63.5
                    2010                483               32.2
                    2011                376               28.4
                    2012                420               31.5
         8          2006                503               31.8
                    2007                434               28.8
                    2008                581               38.7
                    2009                801               52.4
                    2010                447               28.8
                    2011                395               26.1
                    2012                386               30.7
         All Grades 2006               3457               41.0
                    2007               3674               40.0
                    2008               4406               49.5
                    2009               5404               62.5
                    2010               2827               34.0
                    2011               2767               34.4
                    2012               2862               37.2

[1568 rows x 12 columns]

In [496]:
english_2006_score2 = english_2006_score
english_2006_score2 = english_2006_score2.reset_index()
english_2006_score2.head()

,District,Grade,Year,Number Tested,Mean Scale Score,Num Level 1,Pct Level 1,Num Level 2,Pct Level 2,Num Level 3,Pct Level 3,Num Level 4,Pct Level 4,Num Level 3 and 4,Pct Level 3 and 4
0,1,3,2006,808,663,89,11.0,215,26.6,462,57.2,42,5.2,504,62.4
1,1,3,2007,826,659,94,11.4,242,29.3,427,51.7,63,7.6,490,59.3
2,1,3,2008,852,662,60,7.0,270,31.7,449,52.7,73,8.6,522,61.3
3,1,3,2009,901,667,45,5.0,221,24.5,553,61.4,82,9.1,635,70.5
4,1,3,2010,848,669,137,16.2,276,32.5,272,32.1,163,19.2,435,51.3

In [504]:
eng_scr = english_2006_score2[(english_2006_score2.Grade == '6') & (english_2006_score2.Year== 2006)]
eng_scr = eng_scr.reset_index()
eng_scr.head()

,index,District,Grade,Year,Number Tested,Mean Scale Score,Num Level 1,Pct Level 1,Num Level 2,Pct Level 2,Num Level 3,Pct Level 3,Num Level 4,Pct Level 4,Num Level 3 and 4,Pct Level 3 and 4
0,21,1,6,2006,855,653,58,6.8,346,40.5,363,42.5,88,10.3,451,52.7
1,70,2,6,2006,2106,666,76,3.6,529,25.1,1169,55.5,332,15.8,1501,71.3
2,119,3,6,2006,1473,651,124,8.4,618,42.0,572,38.8,159,10.8,731,49.6
3,168,4,6,2006,1409,642,124,8.8,676,48.0,552,39.2,57,4.0,609,43.2
4,217,5,6,2006,1224,633,159,13.0,638,52.1,407,33.3,20,1.6,427,34.9

In [505]:
mean_eng_scr = eng_scr['Mean Scale Score']

In [506]:
check6 = mean_eng_scr
englishScore = pd.DataFrame(Output_SAT['SAT Critical Reading Avg. Score'] + Output_SAT['SAT Writing Avg. Score'])
englishScore = englishScore[0:32]
englishScore.index = check6.index
check7 = pd.concat([check6, englishScore], axis=1)
check7.info()

In [510]:
check7 ['eng_avg_SAT'] = check7[0]
check7 ['eng_scor_2006'] = check7[]

    Mean Scale Score           0  eng_avg_SAT
0                653  837.333333   837.333333
1                666  843.517241   843.517241
2                651  841.923077   841.923077
3                642  785.857143   785.857143
4                633  808.555556   808.555556
5                634  757.700000   757.700000
6                624  750.533333   750.533333
7                635  759.066667   759.066667
8                633  745.285714   745.285714
9                643  786.192308   786.192308
10               640  766.117647   766.117647
11               632  717.600000   717.600000
12               636  814.500000   814.500000
13               637  778.714286   778.714286
14               649  773.909091   773.909091
15               630  720.250000   720.250000
16               634  758.500000   758.500000
17               641  749.071429   749.071429
18               635  726.250000   726.250000
19               654  778.000000   778.000000
20               659  782.727273   782.727273
21               656  908.800000   908.800000
22               644  710.000000   710.000000
23               648  808.000000   808.000000
24               666  841.090909   841.090909
25               677  890.000000   890.000000
26               651  796.272727   796.272727
27               654  873.545455   873.545455
28               645  772.888889   772.888889
29               653  867.500000   867.500000
30               654  896.250000   896.250000
31               640  731.285714   731.285714